# Generated by Django 5.0.6 on 2024-06-27 00:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('author', models.CharField(max_length=100)),
                ('publication_date', models.DateField()),
                ('isbn', models.CharField(max_length=20)),
                ('checked_out', models.BooleanField(default=False)),
                ('reader', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='user.reader')),
            ],
        ),
    ]
