# Generated by Django 5.0.6 on 2024-07-20 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_remove_book_checked_out_remove_book_reader_checkout'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='genre',
            field=models.CharField(choices=[('FANTASY', 'Fantasy'), ('SCIENCE_FICTION', 'Science Fiction'), ('ACTION_ADVENTURE', 'Action & Adventure'), ('MYSTERY', 'Mystery'), ('HORROR', 'Horror'), ('THRILLER_SUSPENSE', 'Thriller & Suspense'), ('HISTORICAL_FICTION', 'Historical Fiction'), ('ROMANCE', 'Romance'), ('CONTEMPORARY_FICTION', 'Contemporary Fiction'), ('MAGICAL_REALISM', 'Magical Realism'), ('GRAPHIC_NOVEL', 'Graphic Novel'), ('SHORT_STORY', 'Short Story'), ('YOUNG_ADULT', 'Young Adult'), ('MEMOIR_AUTOBIOGRAPHY', 'Memoir & Autobiography'), ('BIOGRAPHY', 'Biography'), ('FOOD_DRINK', 'Food & Drink'), ('ART_PHOTOGRAPHY', 'Art & Photography'), ('SELF_HELP', 'Self-help'), ('HISTORY', 'History'), ('TRAVEL', 'Travel'), ('TRUE_CRIME', 'True Crime'), ('HUMOR', 'Humor'), ('GUIDE_HOW_TO', 'Guide/How-to'), ('RELIGION_SPIRITUALITY', 'Religion & Spirituality'), ('HUMANITIES_SOCIAL_SCIENCES', 'Humanities & Social Sciences'), ('PARENTING_FAMILIES', 'Parenting & Families'), ('SCIENCE_TECHNOLOGY', 'Science & Technology'), ('CHILDRENS', "Children's"), ('MISCELLANEOUS', 'Misc.')], default='Misc.', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='book',
            name='issn',
            field=models.CharField(default=0, max_length=20),
            preserve_default=False,
        ),
    ]
